#!/usr/bin/env python3
"""Emit the DSP bring-up sine table as a DSP56001 P-memory section.

The table is data, but it is assembled into P memory on purpose: the
stage-two loader (src/dsp/stage2_loader.asm) transports P sections only, so
initialized X or Y data cannot reach the DSP through it. The kernel copies
this section into internal Y at boot.

Each word is already positioned for the SSI's 16-bit word length: the sample
occupies the top 16 bits of the 24-bit word, so the render loop is a table
read and two stores with no shift.
"""

from __future__ import annotations

import argparse
import math


def sine_words(entries: int, amplitude: int) -> list[int]:
    words: list[int] = []
    for index in range(entries):
        value = round(amplitude * math.sin(2.0 * math.pi * index / entries))
        # Saturate rather than wrap: a rounded full-scale amplitude can reach
        # 32768, which would otherwise fold to the most negative sample.
        value = max(-32768, min(32767, value))
        words.append((value & 0xFFFF) << 8)
    return words


def emit(entries: int, amplitude: int, width: int = 4) -> str:
    words = sine_words(entries, amplitude)
    lines = [
        "; Generated by tools/generate_tone_table.py; do not edit.",
        f"; {entries} entries, peak amplitude {amplitude} of 32767, 16-bit",
        "; samples left-justified in each 24-bit word.",
        "tone_table_image:",
    ]
    for offset in range(0, len(words), width):
        chunk = words[offset : offset + width]
        lines.append("        dc      " + ",".join(f"${word:06x}" for word in chunk))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--entries",
        type=int,
        default=256,
        help="table length; must equal TONE_TABLE_WORDS in protocol.inc",
    )
    parser.add_argument(
        "--amplitude",
        type=int,
        default=8192,
        help="peak sample value (default 8192, a quarter of full scale)",
    )
    arguments = parser.parse_args()
    if arguments.entries < 2 or arguments.entries & (arguments.entries - 1):
        raise SystemExit("error: --entries must be a power of two of at least 2")
    if not 1 <= arguments.amplitude <= 32767:
        raise SystemExit("error: --amplitude must be in 1..32767")
    print(emit(arguments.entries, arguments.amplitude), end="")


if __name__ == "__main__":
    main()
